### ISSUE TITLE
failed to load: not compatible with current version of notepad ++

### ISSUE THREAD

**Issue by rugabunda** [gurikbal/Remove_dup_lines#2]
7.8 64

**Comment by gurikbal** [comment]
but there Remove_Duplicate_Lines.dll works

Notepad++ v7.8   (64-bit)
Build time : Oct  7 2019 - 00:55:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll Remove_Duplicate_Lines.dll

**Comment by gurikbal** [comment]
> 7.8 64

but there Remove_Duplicate_Lines.dll works

Notepad++ v7.8 (64-bit)
Build time : Oct 7 2019 - 00:55:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll Remove_Duplicate_Lines.dll

**Comment by rugabunda** [comment]
![like this](https://user-images.githubusercontent.com/38260267/67657891-fa627580-f94f-11e9-8fc6-42bbc9af57f3.png)

**Comment by rugabunda** [comment]
windows 10 
![plusplus](https://user-images.githubusercontent.com/38260267/67657947-2251d900-f950-11e9-9c43-e49b4f69b5e5.png)

**Comment by gurikbal** [comment]
what you accept if i said `I'm here at win 10`

![_002](https://user-images.githubusercontent.com/36083297/67666450-d45dc500-f991-11e9-9076-7473112d1357.gif)

**Comment by gurikbal** [comment]
this issue can be fixed soon but you have to do proof it
https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/releases

**Comment by gurikbal** [comment]
64bit support
https://github.com/gurikbal/Remove_dup_lines/releases/tag/1.2.0.0
