### ISSUE TITLE
Used in Chinese, There will be strange characters

### ISSUE THREAD

**Issue by xspoco** [gurikbal/Remove_dup_lines#4]
nice plugin, but used in chinese, there will be strange characters.
![2019-12-31_02-56-06](https://user-images.githubusercontent.com/19290455/71596149-760fb700-2b79-11ea-8d82-ec4d0384b6fa.gif)

**Comment by gurikbal** [comment]
> nice plugin, but used in chinese, there will be strange characters.


yes it can be solved by return encoding to UTF8 
you should attach this file also.

**Comment by xspoco** [comment]
> > nice plugin, but used in chinese, there will be strange characters.
> 
> yes it can be solved by return encoding to UTF8
> you should attach this file also.

Whether I use utf8 or gb2312, is the same problem.

![2019-12-31_23-42-01](https://user-images.githubusercontent.com/19290455/71626261-415a3900-2c27-11ea-8549-daef99c96ab5.gif)

[txt-gb2312.txt](https://github.com/gurikbal/Remove_dup_lines/files/4012996/txt-gb2312.txt)
[txt-utf8.txt](https://github.com/gurikbal/Remove_dup_lines/files/4012997/txt-utf8.txt)

**Comment by gurikbal** [comment]
but i removed duplicate lines successfully

https://youtu.be/OP_VqD7lCGw

**Comment by xspoco** [comment]
i do not know why... i install a new system new notepad++ new plugin ,still have the same problem..:fearful: 
![2020-01-02_05-20-58](https://user-images.githubusercontent.com/19290455/71646253-37683100-2d20-11ea-99ac-792aff3cb627.gif)

**Comment by xspoco** [comment]
I know why..
In the Chinese version system, 
Language for non-Unicode programs default setting is Chinese(Simplified,China).
must select options : [Beta: Use Unicode UTF-8 for worldwide  language support]
or
change Current system locale: English(United States).
Then it can be  removed duplicate lines successfully.
![image](https://user-images.githubusercontent.com/19290455/71726318-b4ef8680-2e71-11ea-8a18-c2933dd5af8b.png)
