### ISSUE TITLE
Plugin results in attempt to access C:\windows\win.ini

### ISSUE THREAD

**Issue by Gitoffthelawn** [gurikbal/Remove_dup_lines#5]
**_Thank you for this excellent plugin!_**

### Description of the Issue
Notepad++ v7.8.2 will try to access `c:\windows\win.ini` when 'Remove Duplicate Lines' plugin v1.2.0.0 is installed.  This does not happen when the plugin is not installed.

### Steps to Reproduce the Issue

1.  Download and run FileAccessErrorView from https://www.nirsoft.net/utils/file_access_error_view.html (it's portable - no installation needed)
2.  Download NPP 32-bit portable edition v7.8.2 and extract it into a folder named NPPTEST
3.  Download Remove Duplicate Lines (`Remove_dup_lines_x86.zip`) v1.2.0.0
4.  Extract `Remove_dup_lines_x86.zip` into `NPPTEST\plugins\Remove Duplicate Lines`
5.  Open NPP
6.  Close NPP 
7.  Notice in FileAccessErrorView that Notepad++ tries to access `C:\windows\win.ini`

*This does not happen when this plugin is not installed.*

### Expected Behavior
Not try to access c:\windows\win.ini

### Actual Behavior
NPP tries to access c:\windows\win.ini

### Debug Information

Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : ..\NPPTEST\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 (64-bit) 
OS Build : 7601.0
Plugins : Remove Duplicate Lines.dll

**Comment by Gitoffthelawn** [comment]
Thank you.  Is a release with the fix forthcoming?

**Comment by Gitoffthelawn** [comment]
> Thank you. Is a release with the fix forthcoming?

@gurikbal Ping.

**Comment by gurikbal** [comment]
hi

**Comment by Gitoffthelawn** [comment]
Thank you! :)
