### ISSUE TITLE
removes CR\LF at the end of selection

### ISSUE THREAD

**Issue by RobciuW** [gurikbal/Remove_dup_lines#9]
Description of the problem:
- select text in a middle of a document
- run Remove Dup Lines

the last CR/LF is the selected text is removed, moving anything below selected text UP.

Example:
Before:
    Text Above
    Selected Text 1
    Selected Text 1
    Selected Text 2
    Selected Text 3
    Text Below
    
After:
    Text Above
    Selected Text 1
    Selected Text 2
    Selected Text 3Text Below

The 'Text Below" moves to line above

**Comment by gurikbal** [comment]
use plugin version 13.0.0
![WonderFox_Video_Recording_002_001](https://user-images.githubusercontent.com/36083297/118687937-30619600-b823-11eb-85d5-92aa85545082.gif)
